<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\eNote.Domain\eNote.Domain.csproj" />
  </ItemGroup>
</Project>
