<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-eNote.Worker-62139b86-e153-4bd5-b412-5418df10c189</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eNote.Infrastructure\eNote.Infrastructure.csproj" />
    <ProjectReference Include="..\eNote.Contracts\eNote.Contracts.csproj" />
  </ItemGroup>
</Project>
