global using Xunit;
global using eNote.Application.Common.Exceptions;
global using eNote.Application.Common.Interfaces;
global using eNote.Application.Common.Time;
global using eNote.Domain.Entities.Academic;
global using eNote.Domain.Entities.Identity;
global using eNote.Domain.Entities.Rentals;
global using eNote.Domain.Enums;
global using eNote.Infrastructure.Data;